name: CI/CD to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:latest

      - name: Copy SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > anykeypair.pem
          chmod 600 anykeypair.pem

      - name: SSH and Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i anykeypair.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:latest
            docker stop devops-final-project || true && docker rm devops-final-project || true
            docker run -d --name devops-final-project -p 80:5000 ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:latest
          EOF