name: Deploy to EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-final-project:latest .

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-final-project:latest

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/devops-final-project:latest
          docker stop myapp || true && docker rm myapp || true
          docker run -d -p 80:80 --name myapp ${{ secrets.DOCKER_USERNAME }}/devops-final-project:latest