name: CI/CD to EC2 with Docker and ZAP Scan

on:
  push:
    branches:
      - sectest

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:latest

      - name: Copy SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > anykeypair.pem
          chmod 600 anykeypair.pem

      - name: SSH and Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i anykeypair.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:latest
            docker stop devops-final-project || true && docker rm devops-final-project || true
            docker run -d --name devops-final-project -p 80:5000 ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:latest
          EOF

      - name: Wait for App to Be Available
        run: sleep 5  # adjust if your app takes longer

      - name: Fix permissions for Docker volume
        run: sudo chmod -R 777 .

      - name: Run OWASP ZAP DAST Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk -t zaproxy/zap-stable zap-baseline.py \
            -t http://${{ secrets.EC2_HOST }} -l WARN \
            -r zap_report.html \
            -J zap_report.json \
            -x zap_report.xml || true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: |
            zap_report.html
            zap_report.json
            zap_report.xml
